### ISSUE TITLE
init project

### ISSUE THREAD

**Issue by stoopidJSON** [StoopidCompany/Code-AINATOR#1]
### Task
The thing needs to be a thing.

### Acceptance Criteria
- [x] is a cli tool
- [x] can scan a code directory using a `-d` flag
- [x] can perform a quick summary using `-q` flag
- [x] can perform detailed analysis using `-a` flag
- [x] can output to file using `-o` flag
- [x] can delete projects from memory using `-r` flag
- [ ] (_optional_) can add code comments to code in scanned directory with a -c` flag

### Notes
we may want to make it so the detailed analysis works with additional flags to _use_ that analysis. Like writing a README or something. we also may want it to be able to perform the analysis and then on secondary requests ask it to write certain documents or even point to a document and then say make a new document like that using the information.
