### ISSUE TITLE
make better at setup and stuff

### ISSUE THREAD

**Issue by stoopidJSON** [StoopidCompany/Code-AINATOR#10]
### Task
The code scans should look for things like user config and environment variable usage so that can be specifically addressed in thigns like README and setup docs.

### Acceptance Criteria
- [ ] analysis tracks config options
- [ ] analysis tracks environment variables
- [ ] analysis tracks other possible setup stuff

### Notes
