### ISSUE TITLE
user config

### ISSUE THREAD

**Issue by revjtanton** [StoopidCompany/Code-AINATOR#3]
### Task
Users should be able to provide their own config to override defaults for things.

### Acceptance Criteria
- [ ] can pass an argument for a config file location
- [ ] config can override prompts
- [ ] config can override file types
- [ ] config can override manifest types
- [ ] (_optional_) config can override other things I haven't thought about.

### Notes
