### ISSUE TITLE
in-line documentation

### ISSUE THREAD

**Issue by revjtanton** [StoopidCompany/Code-AINATOR#5]
### Task
Add a feature to be able to generate in-line documentation for the code

### Acceptance Criteria
- [ ] a new feature to take a code file and add in-line documentation to it
- [ ] be able to output the adjusted code to a safe place as to not override the code as it is
- [ ] (_optional_) be able to specify the documentation standard in config or something

### Notes
