### ISSUE TITLE
package this sucker

### ISSUE THREAD

**Issue by revjtanton** [StoopidCompany/Code-AINATOR#7]
### Task
This should be available as a thing you can install via something.

### Acceptance Criteria
- [ ] packaged up and versioned 
- [ ] CICD stuffs to version and build and deploy
- [ ] can be installed via pip
- [ ] can be installed via Homebrew
- [ ] (_optional_) can be installed via Chocolaty
- [ ] (_optional_) can be installed via apt, yum, etc.

### Notes
